linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - varcheck
    - vet

linters-settings:
  goimports:
    local-prefixes: github.com/pavel-snyk/terraform-provider-snyk

output:
  format: tab

run:
  deadline: 10m
